### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by gioger** [riccardo-franchi/Triangular-billiard#13]
Here is a brief checklist of what is left to do:

**Work on `main.cpp`**.
  - [x] we want the user to define $\mu$ and $\sigma$ of the PDFs of both $y_0$ and $\theta$.
  - [x] we want, too, the user to be able to give commands through the command line (e. g. generating a test with $N$ entries, prints statistics, ...); as reference, use the [6th laboratory](https://github.com/Programmazione-per-la-Fisica/labs2022/tree/main/lab6#un-main-program-che-utilizza-le-nuove-funzionalit%C3%A0).
  - [x] it would be, in my opinion, useful to implement it such as the statistics are directly saved on a text file
  - [x] Make it possible to vary $\ell$ and keep the particles constant
  - [x] Use namespaces
  - [x] Reimplment statistics' tests that were removed
  - [x] maybe add some tests in `statistics.test.cpp`
 
**Further improvements**
Consider more generic cases (e.g. $\alpha$ not constant throughout the simulation)

Please note that _Further improvements_ may not be necessary, neither required.
